### ISSUE TITLE
CocosSharp

### ISSUE THREAD

**Issue by KoiKoi2000** [robotlegs-sharp/robotlegs-sharp-framework#9]
I try to run the Robotlegs-Framework in CocosSharp, is there a documentation / example.. It will not be run.

**Comment by prankard** [comment]
Hi KoiKoi,

Thanks for your interest in the Robotlegs Framework.

Sorry for the late reply, but I hadn't ever tested Robotlegs in or built anything with the CocosSharp framwork before.

I've also not tested the framework outside of Unity3D in a while, and I had the bundles incorrect. I have subsequently fixed and have updated the framework. So it would have thrown an error on initialization. This has now been fixed and has been pushed.

After testing, it looks like the basic framework should work.I've included a sample on my namespace:
https://github.com/prankard/cocossharp-robotlegs-sharp-example

The only CocosSharp specific class I included to get it running, is a basic [CCSpriteView](https://github.com/prankard/cocossharp-robotlegs-sharp-example/blob/master/win32/Robotlegs/Bender/Platforms/CocosSharp/Extensions/Mediation/Impl/CCSpriteView.cs) and optional [CCSpriteEventView](https://github.com/prankard/cocossharp-robotlegs-sharp-example/blob/master/win32/Robotlegs/Bender/Platforms/CocosSharp/Extensions/Mediation/Impl/CCSpriteEventView.cs). You might want to overload some other CC classes to use in order to be mediated.

To get more help, have a look at the [docs](https://github.com/robotlegs-sharp/robotlegs-sharp-framework/blob/master/readme.md), in particular the '[A Brief Overview](https://github.com/robotlegs-sharp/robotlegs-sharp-framework/blob/master/docs/ABriefOverview.md)' guide.

And although the basic framework will function well. If you'd like some extra features. Consider looking at the [Adding a Platform](https://github.com/robotlegs-sharp/robotlegs-sharp-framework/blob/master/docs/platforms/AddingAPlatform.md) section. I would only do this however, once you are familiar with the framework.

Thanks,

James

**Comment by KoiKoi2000** [comment]
Hey James,

thank you very much, i will check it in the next days! I starting with CocosSharp and have right now not the complete know-how. I was a long time Flash-Dev and love Robotslegs.

**Comment by prankard** [comment]
Thanks, I'll close this issue for now. If you have any more questions about integration with cocos sharp feel free to re-open.

**Comment by KoiKoi2000** [comment]
I have a Problem :(

you use:
            context.injector.Map<CCWindow>().ToValue(mainWindow);
            context.injector.Map<CCApplication>().ToValue(application);

I create a Mobile Project:
But there is no CCWindow and CCApplication. For the Initialize-Process :/

I have to use:

public class StartupGame 
                .....
		public void setupAppliction(UIApplication application, UIWindow window)
		{
			context.injector.Map<UIApplication>().ToValue(application);
			context.injector.Map<UIWindow>().ToValue(window);
			context.Initialize();
		}
                ......

See a Example-Project:
https://bitbucket.org/KoiKoi/cocossharpkoi/src

I cant reopen this ticket, maybe its too old :D

Thank you very much!!!!
